spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/main;
    username: test
    password: test
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  cas:
    server-url-prefix: https://cas.spbstu.ru
    server-login-url: https://cas.spbstu.ru/login
    client-host-url: https://localhost:8080
    validation-type: CAS

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: 12345a
    keyStoreType: PKCS12
    keyAlias: tomcat

#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 50fa7d5106382aac6f1d
#            clientSecret: f511fce858bba1b17ed64cab677f2b9cb95d77b3
